export const Types = {

    NUgetnotificationsUser: '[NU] get notifications',
    NUupdateNotificationsUser: '[NU] update notifications',
    NUupdateNotificationsUserUpdate: '[NU] update notifications update',
    // 
    MGRespondMessages: '[MG] respond message',
    MGStopRespondMessages: '[MG] stop respond message',
    MGScrollMessageOutGing: '[MG] scroll message outgoing',
    MGScrollMessageClear: '[MG] scroll message clear',
    MGRemoveMessage: '[MG] remove message',
    // 
    ivgetImageVideo: '[IV] get imageVideo',
    ivsetImageVideo: '[IV] set imageVideo',
    ivcreateImageVideo: '[IV] create ImageVideo',
    ivUploadFinish: '[IV] upload finish',
    ivUpload: '[IV] upload',
    ivSetImageVideo: '[IV] set ImageVideo',
    ivClearSetImageVideo: '[IV] clear set ImageVideo',
    ivUpdateImageVideo: '[IV] update ImageVideo',
    ivDeleteImageVideo: '[IV] delete ImageVideo',
    // 
    blgetBeleaver: '[BL] get beleaver',
    blcreateBeleaver: '[BL] create beleaver',
    blUploadFinish: '[BL] upload finish',
    blUpload: '[BL] upload',
    blSetBeleaver: '[BL] set beleaver',
    blClearSetBeleaver: '[BL] clear set beleaver',
    blUpdateBeleaver: '[BL] update beleaver',
    blDeleteBeleaver: '[BL] delete beleaver',
    // 
    nbGetVideo: '[NB] get video',
    nbcreateVideo: '[NB] create Video',
    nbSetVideo: '[NB] set Video',
    nbSetVideoForm: '[NB] set Video form',
    nbClearSetVideo: '[NB] clear set Video',
    nbUpdateVideo: '[NB] update Video',
    nbDeleteVideo: '[NB] delete Video',
    nbUpload: '[NB] upload nb',
    nbUploadFinish: '[NB] upload finish nb',
    // 
    vwdgetVideoWordOfTheDay: '[VWD] get VideoWordOfTheDay',
    vwdsetVideoWordOfTheDay: '[VWD] set VideoWordOfTheDay',
    vwdcreateVideoWordOfTheDay: '[VWD] create VideoWordOfTheDay',
    vwdcreateVideoWordOfTheDayNew: '[VWD] create VideoWordOfTheDayNew',
    vwdSetVideoWordOfTheDay: '[VWD] set VideoWordOfTheDay',
    vwdModalOpen: '[VWD] modal open',
    vwdModalClose: '[VWD] modal close',
    vwdSetVideoWordOfTheDayForm: '[VWD] set VideoWordOfTheDay form',
    vwdClearSetVideoWordOfTheDay: '[VWD] clear set VideoWordOfTheDay',
    vwdUpdateVideoWordOfTheDay: '[VWD] update VideoWordOfTheDay',
    vwdDeleteVideoWordOfTheDay: '[VWD] delete VideoWordOfTheDay',
    vwdUpload: '[VWD] upload vwd',
    vwdUploadFinish: '[VWD] upload finish vwd',
    vwdPaginateVideo: '[VWD] paginate video',
    // 
    ntsGetNota: '[NTS] get nota',
    ntsCrearNota: '[NTS] crear nota',
    ntsUpdateNota: '[NTS] update nota',
    ntsDeleteNota: '[NTS] delete nota',
    ntsSetDeleteNota: '[NTS] set delete nota',
    ntsSetNota: '[NTS] set nota',
    ntsClearSetNota: '[NTS] clear set nota',
    // 
    vsgetVerse: '[VS] get verse',
    vsBook: '[VS] get book',
    vsBookClear: '[VS] clear book',
    vsSearchBibleTrue: '[VS] search bible true',
    vsSearchBibleFalse: '[VS] search bible false',
    // 
    bdActivefilter: '[BD] active filter',
    bdActivePaginate: '[BD] active paginate',
    bdClearActivePaginate: '[BD] clear active paginate',
    bdSetShow: '[BD] set show',
    bdSetHide: '[BD] set hide',
    // 
    ntDeleteNotification: '[NT] delete notification',
    ntNotificacionesCargadas: '[NT] notificaciones cargadas',
    ntCargarNotificaciones: '[NT] cargar notificaciones',
    ntRemoveNewNotificaciones: '[NT] remove new notificaciones',
    // 
    chtTyping: '[CHT] typing',
    chtImageMessage: '[CHT] image message',
    chtClearState: '[CHT] clear state',
    chtUsuariosCargados: '[CHT] usuarios cargados',
    chtCargarChat: '[CHT] cargar chat',
    chtActiveChat: '[CHT] active chat',
    chtActiveMessage: '[CHT] active message',
    chtClearChatActive: '[CHT] clear chat active',
    // 
    skStatusSocket: '[SK] status socket',
    // 
    ytgetYoutube: '[YT] get Youtube',
    ytcreateYoutube: '[YT] create Youtube',
    ytcreateYoutubeNew: '[YT] create Youtube new',
    ytSetYoutube: '[YT] set Youtube',
    ytSetYoutubeForm: '[YT] set Youtube form',
    ytClearSetYoutube: '[YT] clear set Youtube',
    ytUpdateYoutube: '[YT] update Youtube',
    ytDeleteYoutube: '[YT] delete Youtube',
    ytSetYoutubeStart: '[YT] set Youtube start',
    ytPaginateYoutube: '[YT] paginate Youtube',
    // 
    cocreateContact: '[CO] create Contact',
    cogetContacts: '[CO] get Contacts',
    cocreateContactAdmin: '[CO] create Contact Admin',
    coSetContact: '[CO] set Contact',
    coSetContactForm: '[CO] set Contact form',
    coClearSetContact: '[CO] clear set Contact',
    coUpdateContact: '[CO] update Contact',
    coDeleteContact: '[CO] delete Contact',
    coPaginateContact: '[CO] paginate Contact',
    coCargarContact: '[CO] cargar Contact',
    // 
    cagetCapsules: '[CA] get Capsules',
    caSetCapsule: '[CA] set Capsule',
    caSetCapsuleStart: '[CA] set Capsule start',
    // 
    gagetGallerys: '[GA] get Gallerys',
    gaSetGallery: '[GA] set Gallery',
    gacreateGallery: '[GA] create Gallery',
    gacreateGalleryNew: '[GA] create Gallery new',
    gaSetGalleryForm: '[GA] set Gallery form',
    gaClearSetGallery: '[GA] clear set Gallery',
    gaUpdateGallery: '[GA] update Gallery',
    gaDeleteGallery: '[GA] delete Gallery',
    gaPaginateGallery: '[GA] paginate Gallery',
    gaUpload: '[chb] upload ga',
    gaUploadFinish: '[chb] upload finish ga',
    //
    magetMains: '[Ma] get Mains',
    macreateMain: '[Ma] create Main',
    maSetMain: '[Ma] set Main',
    maSetMainForm: '[Ma] set Main form',
    maClearSetMain: '[Ma] clear set Main',
    maUpdateMain: '[Ma] update Main',
    maDeleteMain: '[Ma] delete Main',
    maPaginateMain: '[MA] paginate Main',
    maUpload: '[MA] upload ma',
    maUploadFinish: '[MA] upload finish ma',
    //
    zmAnuncio: '[ZM] anuncio',
    zmgetZooms: '[ZM] get Zooms',
    zmSetZoom: '[ZM] set Zoom',
    zmcreateZoom: '[ZM] create Zoom',
    zmSetZoomForm: '[ZM] set Zoom form',
    zmClearSetZoom: '[ZM] clear set Zoom',
    zmUpdateZoom: '[ZM] update Zoom',
    zmDeleteZoom: '[ZM] delete Zoom',
    zmUpload: '[ZM] upload zm',
    zmUploadFinish: '[ZM] upload finish zm',
    //
    evgetEvents: '[EV] get Events',
    evSetEvent: '[EV] set Event',
    evcreateEvent: '[EV] create Event',
    evSetEventForm: '[EV] set Event form',
    evClearSetEvent: '[EV] clear set Event',
    evUpdateEvent: '[EV] update Event',
    evDeleteEvent: '[EV] delete Event',
    evPaginateEvent: '[EV] paginate Event',
    evUpload: '[EV] upload ev',
    evUploadFinish: '[EV] upload finish ev',
    //
    ptgetPetitions: '[PT] get Petitions',
    ptgetMyPetitions: '[PT] get My Petitions',
    ptgetPetitionesUser: '[PT] get Petitiones User',
    ptgetPetitionSinCuenta: '[PT] get Petition Sin Cuenta',
    ptSetPetition: '[PT] set Petition',
    ptSetPetitionesUser: '[PT] set Petitiones User',
    ptSetPetitionSinCuenta: '[PT] set Petition Sin Cuenta',
    ptClearSetPetition: '[PT] clear set Petition',
    ptCreatePetition: '[PT create Petition u',
    ptCreatePetitionNew: '[PT create Petition',
    ptCreatePetitionMyPetitions: '[PT create Petition my petitions',
    ptUpdatePetition: '[PT Update Petition', 
    ptDeletePetition: '[PT Delete Petition', 
    ptPaginatePetition: '[PT] paginate petition',
    ptPaginatePetitionUser: '[PT] paginate petition user',
    ptPaginatePetitionSinCuenta: '[PT] paginate petition sin cuenta',
    ptDeletePetitionesUser: '[PT] delete Petitiones User',
    ptDeletePetitionSinCuenta: '[PT] delete Petition Sin Cuenta',
    //
    migetSeries: '[Mi] get series',
    miSetSerie: '[Mi] set serie',
    miSetSerieShow: '[Mi] set serie show',
    micreateSerie: '[Mi] create serie',
    micreateSerieNew: '[Mi] create serie new',
    miSetSerieHide: '[Mi] set serie hide',
    miSetSerieStart: '[Mi] set serie start',
    miUpdateSerie: '[Mi] update serie',
    miDeleteSerie: '[Mi] delete serie',
    miPaginateSerie: '[Mi] paginate serie',
    miUpload: '[Mi] upload mi',
    miUploadFinish: '[Mi] upload finish mi',
    //
    sktgetBosquejos: '[SKT] get bosquejos',
    sktSetBosquejo: '[SKT] set bosquejo',
    sktSetBosquejoStart: '[SKT] set bosquejo start',
    sktcreateBosquejo: '[SKT] create bosquejo',
    sktcreateBosquejonew: '[SKT] create bosquejo new',
    sktClearSetBosquejo: '[SKT] clear set bosquejo',
    sktUpdateBosquejo: '[SKT] update bosquejo',
    sktDeleteBosquejo: '[SKT] delete bosquejo',
    sktPaginateBosquejo: '[SKT] paginate bosquejo',
    sktUpload: '[SKT] upload skt',
    sktUploadFinish: '[SKT] upload finish skt',
    //
    authChecking: '[Auth] checking login state',
    authCheckingFinish: '[Auth] finish checking login state',
    authLogin: '[Auth] login ',
    authStartRegister: '[Auth] start register ',
    authStartGetUsers: '[Auth] start Get Users ',
    authStartUpdateUser: '[Auth] start update User ',
    authStartDeleteUser: '[Auth] start delete User ',
    authStartTokenRenew: '[Auth] start token renew ',
    authLogout: '[Auth] logout ',
    authSetUser: '[Auth] set user',
    authActiveSetUser: '[Auth] set user list',
    authModalOpen: '[Auth] modal open',
    authSetUserRegister: '[Auth set user register',
    authForgotPassword: '[Auth forgot password',
    authImageUser: '[Auth image user',
    authDeleteUser: '[Auth] delete user',
    authUpload: '[Auth] upload auth',
    authUploadFinish: '[Auth] upload finish auth',
    authsetNotificationPost: '[Auth] set notifications post',
    authStartUpdateUserNotification: '[Auth] update user notification',
    authshowFooter: '[Auth] show footer'
}