export const Types = {

    gagetGallerys: '[GA] get Gallerys',
    gacreateGallery: '[GA] create Gallery',
    gaSetGallery: '[GA] set Gallery',
    gaSetGalleryForm: '[GA] set Gallery form',
    gaClearSetGallery: '[GA] clear set Gallery',
    gaUpdateGallery: '[GA] update Gallery',
    gaDeleteGallery: '[GA] delete Gallery',
    // 
    magetMains: '[Ma] get Mains',
    macreateMain: '[Ma] create Main',
    maSetMain: '[Ma] set Main',
    maSetMainForm: '[Ma] set Main form',
    maClearSetMain: '[Ma] clear set Main',
    maUpdateMain: '[Ma] update Main',
    maDeleteMain: '[Ma] delete Main',
    // 
    zmgetZooms: '[ZM] get Zooms',
    zmcreateZoom: '[ZM] create Zoom',
    zmSetZoom: '[ZM] set Zoom',
    zmSetZoomForm: '[ZM] set Zoom form',
    zmClearSetZoom: '[ZM] clear set Zoom',
    zmUpdateZoom: '[ZM] update Zoom',
    zmDeleteZoom: '[ZM] delete Zoom',
    // 
    evgetEvents: '[EV] get Events',
    evcreateEvent: '[EV] create Event',
    evSetEvent: '[EV] set Event',
    evSetEventForm: '[EV] set Event form',
    evClearSetEvent: '[EV] clear set Event',
    evUpdateEvent: '[EV] update Event',
    evDeleteEvent: '[EV] delete Event',
    // 
    ptgetPetitions: '[PT] get Petitions',
    ptcreatePetition: '[PT] create Petition',
    ptSetPetition: '[PT] set Petition',
    ptSetPetitionForm: '[PT] set Petition form',
    ptClearSetPetition: '[PT] clear set Petition',
    ptUpdatePetition: '[PT] update Petition',
    ptDeletePetition: '[PT] delete Petition',
    // 
    usSetUser: '[US] set user',
    // 
    migetSeries: '[Mi] get series',
    micreateSerie: '[Mi] create serie',
    miSetSerie: '[Mi] set serie',
    miSetSerieForm: '[Mi] set serie form',
    miClearSetSerie: '[Mi] clear set serie',
    miUpdateSerie: '[Mi] update serie',
    miDeleteSerie: '[Mi] delete serie',
    // 
    sktgetBosquejos: '[SKT] get bosquejos',
    sktcreateBosquejo: '[SKT] create bosquejo',
    sktSetBosquejo: '[SKT] set bosquejo',
    sktClearSetBosquejo: '[SKT] clear set bosquejo',
    sktUpdateBosquejo: '[SKT] update bosquejo',
    sktDeleteBosquejo: '[SKT] delete bosquejo',
    // 
    authChecking: '[Auth] checking login state',
    authCheckingFinish: '[Auth] finish checking login state',
    authLogin: '[Auth] login ',
    authStartRegister: '[Auth] start register ',
    authStartGetUsers: '[Auth] start Get Users ',
    authStartUpdateUser: '[Auth] start update User ',
    authStartDeleteUser: '[Auth] start delete User ',
    authStartTokenRenew: '[Auth] start token renew ',
    authLogout: '[Auth] logout ',
    authSetUser: '[Auth set user',
    authDeleteUser: '[Auth] delete user'
}